changes after review

diff --git a/data-collection/scripts/masquerade b/data-collection/scripts/masquerade
--- a/data-collection/scripts/masquerade
+++ b/data-collection/scripts/masquerade
@@ -1,17 +1,39 @@
 #!/usr/bin/env bash
 
+# Kill the program if any error is encountered
+set -e
+
+# Usage instructions
 helpFunction()
 {
+  bold=$(tput bold)
+  normal=$(tput sgr0)
+  underline=$(tput smul)
   echo ""
-  echo "Usage: $0 -i /path/to/input/file -o /path/to/output/file -s /path/to/secrets/file"
-  echo -e "\t-i Path to input file."
-  echo -e "\t-o Path to output generated file."
-  echo -e "\t-s Path to a file containing key/value secrets."
-  echo -e "\t-f Force overwrite existing file at output path?"
+  echo "Usage: ${bold}masquerade${normal} [${bold}-i${normal} ${underline}file${normal}] [${bold}-o${normal} ${underline}file${normal}] [${bold}-s${normal} ${underline}file${normal}]"
+  echo -e ""
+  echo -e "\t${bold}-i${normal}"
+  echo -e "\t\tPath to input file."
+  echo -e "\t\tThe program will parse the input file looking for bracket-enclosed keys, ex: {{ KEY }}"
+  echo -e ""
+  echo -e "\t${bold}-o${normal} "
+  echo -e "\t\tPath to output generated file."
+  echo -e "\t\tPlease ensure the the user has write permissions."
+  echo -e ""
+  echo -e "\t${bold}-s${normal}"
+  echo -e "\t\tPath to a file containing key/value secrets."
+  echo -e "\t\tEvery line is treated as a different key following the format KEY=VALUE where"
+  echo -e "\t\t${underline}KEY${normal} alpha-numeric and underscore characters"
+  echo -e "\t\t${underline}=${normal} the equal character '=' is a delimiter"
+  echo -e "\t\t${underline}VALUE${normal} any character before newline"
+  echo -e ""
+  echo -e "\t${bold}-f${normal}"
+  echo -e "\t\tForce overwrite existing file at output path."
   echo -e ""
   exit 1
 }
 
+# -o force write defaults to false
 FORCE_WRITE='false'
 
 # Command line options
@@ -29,77 +51,86 @@ done
 # Validate -i param:
 # - input param is not missing
 # - input file is file
-if [ -z "$INPUT_FILE" ]; then
-  echo "-i param is missing."
+if [ -z "${INPUT_FILE}" ]; then
+  echo "error: -i input file param is missing."
   helpFunction
-elif [ ! -f $INPUT_FILE ]; then
-  echo "$INPUT_FILE file not found."
+elif [ ! -f "${INPUT_FILE}" ]; then
+  echo "error: ${INPUT_FILE} input file not found."
   helpFunction
 fi
 
 # Validate -o param:
 # - output param is not missing
 # - output file exists and has specified a forced overwrite
-if [ -z "$OUTPUT_FILE" ]; then
-  echo "-o param is missing."
+if [ -z "${OUTPUT_FILE}" ]; then
+  echo "error: -o output file param is missing."
   helpFunction
-elif [ -f $OUTPUT_FILE ] && [ $FORCE_WRITE == 'false' ]; then
-  echo "File exists at path $OUTPUT_FILE"
-  echo "Supply the -f flag to overwrite the output file."
+elif [ -f "${OUTPUT_FILE}" ] && [ "${FORCE_WRITE}" == 'false' ]; then
+  echo "error: file exists at path ${OUTPUT_FILE}"
+  echo "error: supply the -f flag to overwrite the output file."
   exit 1
 fi
 
 # Validate -s param:
 # - secrets param is not missing
 # - secrets is file
-if [ -z "$SECRETS" ]; then
-  echo "-s param is missing."
+# - secrets is valid format
+if [ -z "${SECRETS}" ]; then
+  echo "error: -s secrets file param is missing."
   helpFunction
-elif [ ! -f $SECRETS ]; then
-  echo "$SECRETS file not found."
+elif [ ! -f "${SECRETS}" ]; then
+  echo "error: ${SECRETS} secrets file not found."
   helpFunction
+else
+  while read -r line
+  do
+    if [[ ! $line =~ ^[a-zA-Z0-9_]*=.+$ ]]; then
+      echo "error: ${line} invalid secret"
+      exit 1
+    fi
+  done < <(grep -Ev '^#' "${SECRETS}")
 fi
 
 # Create temporary directory
 TEMP_DIR=$(mktemp -d -t secrets)
 
 # Check if tmp dir was created
-if [ ! "$TEMP_DIR" ] || [ ! -d "$TEMP_DIR" ]; then
-  echo "Could not create temporary directory."
-  exit 1
+if [ ! "${TEMP_DIR}" ] || [ ! -d "${TEMP_DIR}" ]; then
+  # Fallback to /tmp
+  TEMP_DIR='/tmp/masque'
 fi
 
 # Deletes the temp directory
 function cleanup {
-  rm -rf "$TEMP_DIR"
+  rm -rf "${TEMP_DIR}"
 }
 
 # Register the cleanup function to be called on the EXIT signal
 trap cleanup EXIT
 
 ## Create temporary file path
-TEMP_FILE="$TEMP_DIR/$(basename "$INPUT_FILE")"
+TEMP_FILE="${TEMP_DIR}/$(basename "${INPUT_FILE}")"
 
 # Copy input file to temporary file
-cp ${INPUT_FILE} ${TEMP_FILE}
+cp "${INPUT_FILE}" "${TEMP_FILE}"
 
 # First pass: iterate replacing keys found in template with values found in secrets
-while read line
+while read -r line
 do
   # Extract key/value pairs
-	KEY=$(echo $line | cut -d= -f1)
-	VALUE=$(echo $line | cut -d= -f2)
+	KEY=$(echo "${line}" | cut -d= -f1)
+	VALUE=$(echo "${line}" | cut -d= -f2)
 	# Use sed to replace keys with values
   # Note, accepts space surrounding key
-	sed -i.bak -e "s/{{ *$KEY *}}/$VALUE/g" ${TEMP_FILE}
-done < <(grep -Ev '^#' ${SECRETS})
+	sed -i.bak -e "s/{{ *${KEY} *}}/${VALUE}/g" "${TEMP_FILE}"
+done < <(grep -Ev '^#' "${SECRETS}")
 
 # Second pass: clean-up missed variable brackets
-while read line
+while read -r line
 do
 	# Use sed to replace keys with values
-	sed -i.bak -e "s/{{.*}}//g" ${TEMP_FILE}
-done < <(grep -Ev '^#' ${TEMP_FILE})
+	sed -i.bak -e "s/{{.*}}//g" "${TEMP_FILE}"
+done < <(grep -Ev '^#' "${TEMP_FILE}")
 
 # Move finished working file to ouput
-mv ${TEMP_FILE} ${OUTPUT_FILE}
+mv "${TEMP_FILE}" "${OUTPUT_FILE}"
